# Copyright 2020 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

site_name: Hero-Tools
site_dir: public

theme:
  name: readthedocs
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.expand
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.footer

repo_url: https://iis-git.ee.ethz.ch/hero/hero-tools/
repo_name: hero-tools

nav:
- Home:
  - index.md
  - Getting Started: gs.md
- Sofware:
  - software/index.md
- Platforms:
  - Carfield: platforms/carfield.md
  - Occamy: platforms/occamy.md
  - Milk-V: platforms/milkv.md
